### ISSUE TITLE
Make map display optional and/or accept options 

### ISSUE THREAD

**Issue by freenerd** [mapbox/mapbox-map-matching.js#6]
If I understand https://github.com/mapbox/leaflet-mapmatch//blob/b0740a68c7f735607c5353be6114e51fc2d8f9ba/index.js#L59 correctly, then we are always mapping the returned features directly on the map. We'll want to give the user more control here:

- Make it possible to add options to the displayed feature
- Return features without putting them on the map, so users can do their own sanity checks (confidence, number of distinct features) before displaying on the map

Best would be supporting both I guess.

**Comment by planemad** [comment]
@freenerd to clarify, you mean one can request for just the `matchedGeometeries` FeatureCollection?

**Comment by freenerd** [comment]
```javascript
mapmatch(geojson, function(err, features) {
  // let me do something with the features here, e.g. only use ones with high confidence
  var good_features = $(features).filter(function(f) { return f.properties.confidence > 0.8; });
})
```

**Comment by planemad** [comment]
@freenerd :+1: will do this

**Comment by planemad** [comment]
options available now as documented in the readme
